import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const articles = sqliteTable("articles", {
  id: integer("id").primaryKey({ autoIncrement: true }), headline: text("headline").notNull(), slug: text("slug").notNull().unique(), industry: text("industry").notNull(), frameworkId: integer("framework_id"), tags: text("tags",{mode:"json"}).$type<string[]>().notNull().default([]), summary: text("summary"), heroImageKey: text("hero_image_key"), publishedUrl: text("published_url"), publicationDate: integer("publication_date",{mode:"timestamp"}), seoTitle: text("seo_title"), seoDescription: text("seo_description"), internalNotes: text("internal_notes"), status: text("status",{enum:["idea","research","draft","ready","published","archived"]}).notNull().default("idea"), distributionStatus: text("distribution_status").notNull().default("not_started"), performanceStatus: text("performance_status").notNull().default("pending"), repurposeCompleted: integer("repurpose_completed",{mode:"boolean"}).notNull().default(false), newsletterIncluded: integer("newsletter_included",{mode:"boolean"}).notNull().default(false), createdAt: integer("created_at",{mode:"timestamp"}).notNull(), updatedAt: integer("updated_at",{mode:"timestamp"}).notNull()
});
export const frameworks = sqliteTable("frameworks", { id: integer("id").primaryKey({autoIncrement:true}), name:text("name").notNull().unique(), slug:text("slug").notNull().unique(), description:text("description").notNull(), relationships:text("relationships",{mode:"json"}).$type<number[]>().notNull().default([]) });
export const distributionCopies = sqliteTable("distribution_copies", { id:integer("id").primaryKey({autoIncrement:true}), articleId:integer("article_id").notNull(), platform:text("platform").notNull(), copy:text("copy").notNull(), enabled:integer("enabled",{mode:"boolean"}).notNull().default(true), status:text("status").notNull().default("draft"), scheduledAt:integer("scheduled_at",{mode:"timestamp"}), publishedUrl:text("published_url"), externalPostId:text("external_post_id"), lastError:text("last_error"), updatedAt:integer("updated_at",{mode:"timestamp"}).notNull() });
export const repurposeAssets = sqliteTable("repurpose_assets", { id:integer("id").primaryKey({autoIncrement:true}), articleId:integer("article_id").notNull(), format:text("format").notNull(), content:text("content").notNull(), status:text("status").notNull().default("draft"), updatedAt:integer("updated_at",{mode:"timestamp"}).notNull() });
export const performanceSnapshots = sqliteTable("performance_snapshots", { id:integer("id").primaryKey({autoIncrement:true}), articleId:integer("article_id"), channel:text("channel").notNull(), capturedAt:integer("captured_at",{mode:"timestamp"}).notNull(), metrics:text("metrics",{mode:"json"}).$type<Record<string,number>>().notNull() });
export const editorialEvents = sqliteTable("editorial_events", { id:integer("id").primaryKey({autoIncrement:true}), articleId:integer("article_id").notNull(), type:text("type").notNull(), channel:text("channel"), scheduledAt:integer("scheduled_at",{mode:"timestamp"}).notNull(), status:text("status").notNull().default("scheduled") });
